### ISSUE TITLE
Does the pipeline support phasing of Hi-C data?

### ISSUE THREAD

**Issue by YuboWang1994** [jia-wu-feng/PP2PG#1]
Hi,

Thanks for this pipeline and it's very helpful. 
I'm currently trying to phasing Hi-C data of a haplotype-phased genome, i.e. two genome sequences. I'm wondering whether this pipeline can be used to phase Hi-C data into two datasets just like RNA-seq phasing?

Thanks,
Yubo

**Comment by jia-wu-feng** [comment]
It's hard to say, I haven't tested it. 
I know there is another software for Hi-C phasing, you can try it(https://github.com/Prayforhanluo/HiCHap_master).

**Comment by YuboWang1994** [comment]
OK, thanks a lot. It seems like it may be helpful :)
